# Generated by Django 2.0 on 2022-11-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='voter',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='voting',
            field=models.PositiveIntegerField(),
        ),
    ]
