# Generated by Django 2.0 on 2022-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221113_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.PositiveIntegerField()),
                ('percen', models.PositiveIntegerField()),
            ],
        ),
    ]
