# Generated by Django 2.0 on 2022-11-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_percentages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentages',
            name='percen',
            field=models.FloatField(),
        ),
    ]
