# Generated by Django 2.0 on 2022-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20221116_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
