# Generated by Django 2.0 on 2022-11-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_surveys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='voter',
            field=models.TextField(),
        ),
    ]
