# Generated by Django 2.0 on 2022-11-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
