# Generated by Django 2.0 on 2022-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('normal', 'Votación normal'), ('borda', 'Votación con recuento borda'), ('multi', 'Votación multirespuesta')], default='normal', max_length=50),
        ),
    ]
