# Generated by Django 2.0 on 2022-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='num_votes_M',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='num_votes_O',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='num_votes_W',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
