# Generated by Django 2.0 on 2022-11-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_questiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('normal', 'Votación normal'), ('borda', 'Votación con recuento borda')], default='normal', max_length=50),
        ),
    ]
