# Generated by Django 2.0 on 2022-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20221117_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('normal', 'Votación normal'), ('borda', 'Votación con recuento borda'), ('dhondt', "Votación con sistema D'Hondt")], default='normal', max_length=50),
        ),
    ]
