# Generated by Django 2.0 on 2022-11-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20221123_1713'),
        ('voting', '0006_auto_20221118_1346'),
    ]

    operations = [
    ]
