# Generated by Django 2.0 on 2022-11-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20221122_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='numvotosM',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voting',
            name='numvotosO',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voting',
            name='numvotosW',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
