<<<<<<< HEAD
# Generated by Django 2.0 on 2022-11-18 15:44
=======
# Generated by Django 2.0 on 2022-11-18 13:46
>>>>>>> e2860329066fb2ca16c6242577c96d6bbaad294b

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('M', 'Hombre'), ('W', 'Mujer'), ('O', 'Otro')], default='O', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
