name: 'Terraform Cloud - AWS'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: decide
    steps:
      - uses: actions/checkout@v3
      - uses: javiercavlop/terraform-cloud-actions@v1.0.0
        with:
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
          working-directory: './terraform'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          terraform-version: 1.3.7